databases:
  - name: wine_db_p4pv
    databaseName: wine_db_p4pv
    user: wine_user
    plan: free # бесплатный тариф (можно изменить на нужный)

services:
  - type: web
    name: wine-backend
    env: docker # Render автоматически найдет ваш Dockerfile
    plan: free
    envVars:
      # Render автоматически сгенерирует пароль и хост,
      # поэтому мы передаем их в ваше приложение динамически
      - key: POSTGRES_DB
        value: wine_db_p4pv
      - key: POSTGRES_USER
        value: wine_user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: wine_db_p4pv
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: wine_db_p4pv
          property: host
      # Если ваш код в main.py использует единую строку подключения (DSN), 
      # раскомментируйте блок ниже:
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: wine-db
      #     property: connectionString
